package com.jay.shermassignment.response.responsibleperson

data class Content(
    val address: Any,
    val city: Any,
    val countryId: Any,
    val countryName: Any,
    val dateOfBirth: Any,
    val departmentName: String,
    val emailId: Any,
    val empId: Int,
    val employee: Any,
    val employeeDetails: String,
    val employeeDetailsForPlantEquipment: String,
    val employeeId: Any,
    val employmentTypeName: Any,
    val firstName: String,
    val fullName: String,
    val gender: Any,
    val id: Int,
    val joiningDate: Any,
    val lastName: String,
    val mobile: Any,
    val name: Any,
    val phone: Any,
    val positionName: Any,
    val postCode: Any,
    val reportingTo: Any,
    val siteName: String,
    val stateId: Any,
    val stateName: Any,
    val status: Any,
    val userName: Any
)